// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://seazcwpqhixukvxrrepy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNlYXpjd3BxaGl4dWt2eHJyZXB5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4OTM2ODAsImV4cCI6MjA2ODQ2OTY4MH0.qx3epIyt3UVlacilCDeVWQBsxTrmw6wa2z3tTxzP0Hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});